### ISSUE TITLE
Assertions definitions missing "/** @noSelfInFile */" at start of files?

### ISSUE THREAD

**Issue by dainkaplan** [hazzard993/busted-tstl#1]
Not sure if it is part of my active project setup, but I needed to manually add `/** @noSelfInFile */` to the top of the definitions within `assertions/`, e.g.:

```typescript
/** @noSelfInFile */
declare namespace assert {

```

In order for my busted tests to run correctly. Calls like `assert.are.equals(foo, bar)` were receiving a self parameter as the first argument, and comparing that to the first value passed in, which obviously weren't equal. Manually adding the no self in file annotations resolved the issue.

Is there an expected configuration for the calling project that is required for these definitions to work without modification?

**Comment by hazzard993** [comment]
Nope that is a bug, thanks very much for submitting this issue!

I'll make a new release preventing the self parameter from being used in assertions

**Comment by hazzard993** [comment]
Released version 0.1.1 on npmjs, let me know if you encounter any more unexpected self parameter bugs

**Comment by dainkaplan** [comment]
Super! Thanks for the quick turn around.

**Comment by dainkaplan** [comment]
Confirmed it works now! Thanks, again!
