### ISSUE TITLE
spy.clear() and spy.revert() need "self" parameter

### ISSUE THREAD

**Issue by JesseBrault0709** [hazzard993/busted-tstl#2]
Hello,

I ran into an issue today using the TypeScript/Busted method `spy.revert()`; the generated lua code is `spy.revert()` but actually needs to be `spy:revert()` as noted [here](https://olivinelabs.com/busted/#spies-mocks-stubs). A quick change in the busted.d.ts file of `revert: (this: void) => void;` to `revert: () => void;` (and likewise for `clear`) fixes the issue.

Thank you for this wonderful tool!

**Comment by hazzard993** [comment]
Thanks for the report!

I've made a change and published `busted-tstl@0.1.2-rc.0` so you can try out the changes and see if they are working for you

You can install the package via `npm install busted-tstl@0.1.2-rc.0` or `yarn add busted-tstl@0.1.2-rc.0`

**Comment by hazzard993** [comment]
Released 0.1.2 changes
